### ISSUE TITLE
Bug with nex and warper.

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#100]
Баг с нексом и варпером воспроизвести так:
Зажать выстрел некса, далее когда отпускаем (выстрел некса) !одновременно! ставим варпер. После того как выстрел закончится, юзаем варпер чтоб телепортироваться.
В итоге на нексе потратятся все выстрелы, он заблочится и будет стрелять по одному выстрелу, сменить оружие будет невозможно.
Клиент не обновлял. Спасибо :)

**Comment by nexAkari** [comment]
Fixed in ef7b160, thanks for reporting.
