### ISSUE TITLE
Bug with mg and warper.

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#101]
Небольшой баг с варпером и machinegun. Если поставить варпер когда mg делает последний выстрел и телепортироваться, при этом держа кнопку выстрела secondary fire (держать кнопку выстрела mg), то стелепортируемся мы без зарядов mg и он не будет перезаряжаться до тех пор пока не отпустить кнопку выстрела mg.
Воспроизвести:
1. Выбрать mg и warper.
2. Зажать кнопку sec fire и держать
3. На последнем выстреле поставить warper.
4. Заюзать warper и не отпускать кнопки sec fire.
5. Перезарядки mg не будет пока не отпустить кнопку sec fire. 
П.с. для воспроизведения необходимо держать кнопку sec fire постоянно.

**Comment by nexAkari** [comment]
Fixed in ef7b160, thanks for reporting.
