### ISSUE TITLE
Bug with pryaxe and warper.

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#102]
Баг с топором и варпером кладет сервак.
Как воспроизвести:
1. Выбираем pryaxe и warper.
2. Нажимаем sec fire и отпускаем (чтобы pryaxe полетел), как только он замахнется, ставим варпер и телепортируемся. То есть rmclck -> C -> Q. Задержка между действиями должна быть примерно 0.2 сек.
В итоге вылет серва.

**Comment by nexAkari** [comment]
Fixed in ef7b160, thanks for reporting.
