### ISSUE TITLE
Another bug with pryaxe warper.

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#103]
Небольшой не критичный баг (может и стоит оставить). Можно кидаться несколькими pryaxam`и. 
1. Выбираем карту с большим расстоянием для лучшего теста.
2. Берем pryaxe и warper.
3. Встаем так чтобы было большое расстояние до выстрела.
4. Ставим варпер.
5. Кидаем (далеко) pryaxe.
6. Юзаем варпер.
7. Кидаем далеко pryaxe. 
Таким образом будет 2 летящих pryaxe, когда вернется один сразу же кидаем, вернется второй тоже кидаем. То есть 2 pryaxe летать будут одновременно. Это прекратиться если вернутся оба. Тогда останется один.

**Comment by nexAkari** [comment]
This is not a bug, it's intended.
