### ISSUE TITLE
Jailbreak mode + Zapper sentry bug

### ISSUE THREAD

**Issue by achennu** [nexAkari/RocketMinsta#83]
In Jailbreak game mode, when an abandoned zapper sentry is being taken over, the progress bar shows "Unlocking jail" instead of "Capture progress".

Needs to be fixed.

Which file is the relevant code in?

**Comment by kasymovga** [comment]
qcsrc/client/sbar.qc:

        if(revmode == RMODE_REV)
            s = "Revival progress: ";
        else if(revmode == RMODE_AUTH)
            s = "Authenticating: ";
        else if(gametype == GAME_JAILBREAK)
             s = "Unlocking the jail: ";
        else
             s = "Capture progress: ";

Yep, some hacks here. I will try fix it.

**Comment by kasymovga** [comment]
Ok. Now it must be fixed.
