### ISSUE TITLE
Bug with new weapons.

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#86]
Напишу на русском так проще. 
1. Начало раунда.
2. Кликаем кнопку правой мыши чтобы выбрать второе оружие (Например nex). 
3. В меню меняем оружие на другое (Например на zapper). 
-- Все это сделать надо до начала раунда.

Итог: Нет возможности выбрать главное оружие, зато заппер и некс стреляют primary fire.
С Новым годом:)

**Comment by nexAkari** [comment]
Fixed.
