### ISSUE TITLE
Bug on CA 

### ISSUE THREAD

**Issue by Nimimator** [nexAkari/RocketMinsta#87]
When you go AFK during the CA and go in the spectacting mode, you lose all your points. That's fine. But when after some time you re-join the game, your old time and acc are still there, but not kdr and points. I was wondering was that on purpose or actually a bug? Hope it gets fixed anyways 
[this refers to one match in total]

**Comment by nexAkari** [comment]
I just fixed the playtime stat not resetting when the other scores are reset. Accuracy statistics are currently never reset at all - consider this the intended behaviour for now, but that may change in the future.

**Comment by Nimimator** [comment]
Alright, thanks
