### ISSUE TITLE
Omg damage:)

### ISSUE THREAD

**Issue by Formcd** [nexAkari/RocketMinsta#92]
Если взять шотган и мистик (mystic an eye или как его...), это убийственная смесь, шотган стреляет с маленькой задержкой и с разбросом, очень большой шанс что будет попадание по шарику. В итоге убить очень легко становится (там под 200 урона если не ошибаюсь). Также если использовать ту же связку легко убивать замороженных - наводишь на шарик и 2 выстрела подряд, ничего сделать невозможно. Просьба пофиксить.

**Comment by nexAkari** [comment]
Fixed.
